### PR TITLE
Update readme to 4.8

### PR DESCRIPTION
**Pull request by nimmolo**
The only things changed should be the readmes - i also added the words "in WordPress" after "crossposts" so it's clear which way they are cross posted (i.e., plugin does not cross post your YouTube videos to Vimeo, for example)

### CODE REVIEW

**Review by silviapfeiffer — APPROVED** [review]

**Comment by nimmolo** [comment]
Silvia, on the advice of WP plugins "grand poobah" Ipstenu I had to bump the stable tag in order for the repo to recognize the "update". This ~~should also fix~~ fixed the disappearing banner issue (just a visual asset on the wordpress repo, but helpful for users).

**Correction:**
What she actually said, and i misunderstood, was that i have to update the readme file in the trunk folder, but also identically update the same file in the tags/most-recent-tag folder. *doh!* 

> is it then possible to change the readme.txt without upping the stable 
> tag?  or rather, how do people update the "tested up to" version without 
> changing the stable release tag.

They update the readme for the stable tag AND trunk.

You changed trunk. You have to change BOTH.

-- 
Ipstenu (Mika Epstein)


Anyway, before i understood this properly i went ahead and bumped the SVN tag to 1.1.1, without ANY further changes, to force the upload to sync, and committed it. At least it worked, so now the readme changes and asset banners are finally up on the repo. If you approve i'll merge this, sorry i forgot to merge after the last approval. 

Thankfully, it does not seem to be forcing updates to people who have the plugin installed, because the actual version number of the plugin (as opposed to the SVN tag) didn't change.

Sorry if this is TMI about nothing much, just want you to know what's going on.

**Comment by silviapfeiffer** [comment]
What you have to do is actually somewhat described in the DEVELOPMENT.md file. At the least the first 3 lines are correct:
* edit readme.txt to bump up stable tag
* edit external-videos.php bump up stable tag there, too

You still have to update the version in external-videos.php  !

**Comment by nimmolo** [comment]
Yeah updating the version in external-videos.php is exactly what i did NOT want to do - because it's not a real update. Just an update to the readme.txt to say its still compatible with current wordpress. 

I was mystified how to make the wordpress plugin repo display this readme, because svn repo seemed to be ignoring the commit. But the repo ignores trunk - it is pulling the readme from the (most recent stable) tag folder, which should be an exact duplicate of trunk. Because I hadnt updated the duplicate readme in the tags/1.1 folder, so it was ignoring the updated readme in trunk.

All sorted now. We dont want people downloading a non-update.

**Comment by silviapfeiffer** [comment]
OK, but I prefer the files to be consistent. People don't usually mind updating even if not much changes.

**Pull request merged**
