### PR TITLE
Fix sp_ev_get_all_videos

### PR DESCRIPTION
**Pull request by nimmolo**
array_merge was not working. This is just a quick fix and does not use the new Vimeo API

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
hey @nimmolo sorry for not following up earlier - was your patch for vimeo support ready to merge?

**Comment by nimmolo** [comment]
hi Silvia - almost ready 

got Vimeo's new API working, and I've updated the plugin to use the latest YouTube API too. 

I'm focused now - I can update the Dotsub too. do you have a dotsub test account I can use?

**Comment by silviapfeiffer** [comment]
I made you a collaborator, so you can better work with the repository.

I can email you an account - contact me on silviapfeiffer1@gmail.com

**Comment by nimmolo** [comment]
Not yet! Haha sorry, i've got to figure out the github flow better. Thanks for writing though. 

i'm working on it again. I got Youtube working again, theres a new version of their php api. I will do a pull request with a cleaner version very soon.

The only bummer is the new google api is like 20MB. I've asked them if there's any folders i can toss.

**Comment by nimmolo** [comment]
Silvia, 
I took a break from working on the plugin, but will have an update for you to test soon.

**Comment by silviapfeiffer** [comment]
Excellent, the Christmas break is when I tend to release updates to this plugin!

**Pull request closed without merging**
