### PR TITLE
As long as we're adding assets, here are some banners

### PR DESCRIPTION
**Pull request by nimmolo**
I'm happy to do commits like this if you want to make me a committer, but i'd definitely prefer you review everything still. This is just an addition of plugin repo banners for the as yet uncreated /assets folder. Nothing fancy.

I'm not sure if you can simply create that folder at the root level without doing a version update. Seems like everything on SVN goes by version number (thus the name) but maybe not with /assets folder creation outside of /tags /trunk and /branches.

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
I'll see what I can do to get you svn access. I also can only look at commits at the weekend, but do keep them coming! 😀

**Comment by nimmolo** [comment]
You can make me a plugin committer with one click on the new [WP Plugins Repo admin page](https://wordpress.org/plugins-wp/external-videos/admin/).

I have Versions downloaded and ready to go for SVN use, and i've practiced downloading and checking repos back in.

At present the only thing I will commit is the assets folder 😇

**Comment by silviapfeiffer** [comment]
Hey sorry, had a busy week, promise to do it this weekend!

**Comment by nimmolo** [comment]
OK let me know when you get to it! 
I would definitely like to learn how to do SVN checkouts and commits, so this seems like a good time, with no changes to trunk.

**Comment by silviapfeiffer** [comment]
OK, I just made you a committer!

**Comment by silviapfeiffer** [comment]
I was just reading up https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/ .
The folder that you created will not work via a branches or tags directory, but when you check it into SVN, the assets folder has to be a top level folder.
There's a bit more about it here: https://www.sitepoint.com/publishing-a-plugin-to-the-wordpress-plugin-directory/
Good luck with it! And sorry about the delay!

**Comment by nimmolo** [comment]
Uploaded /assets to top level but apparently the plugins repository is [having sync issues](https://make.wordpress.org/plugins/2016/04/13/assetsreadmes-not-showing-properly-on-plugin-pages/).

**Comment by silviapfeiffer** [comment]
Maybe our changelog is getting too long and we need to move it off into GitHub like is proposed in that thread. I doubt it would still be an issue though. The assets are definitely there though: https://plugins.svn.wordpress.org/external-videos/assets/

**Pull request merged**
