### PR TITLE
Overhaul additional fixes

### PR DESCRIPTION
**Pull request by silviapfeiffer**
Adding some additional things to the overhaul in preparation for release

### CODE REVIEW

**Comment by nimmolo** [comment]
Silvia - just wanted you to know I went through all these commits too

**Comment by silviapfeiffer** [comment]
No worries - did you find out which of the above caused the layout on the settings page to be broken?

**Comment by nimmolo** [comment]
No i didn't! I kept adding your commits and nothing broke it. But i did also put those re-written functions in ev-admin.php, maybe that did it? Still, I reloaded the options page after every commit. Odd!

**Comment by silviapfeiffer** [comment]
Yeah, strange, a new pull from master did it. I'll see if I can replicate it. Gotta do some more other work first.

**Comment by nimmolo** [comment]
ok - please check out the rewrites of those update-post-trash functions in the new PR also

**Comment by silviapfeiffer** [comment]
Sorry - had a bunch of customer support calls to do tonight!

**Pull request merged**
